services:
  anti_social:
    image: postgres:latest
    container_name: anti_social
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_NAME}
    ports:
      - '5434:5432'
    volumes:
      - ./data/social:/var/lib/postgresql
    restart: unless-stopped

  postgres_test:
    image: postgres:latest
    container_name: postgres_test
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_TEST}
    ports:
      - '5433:5432'
    volumes:
      - ./data/test:/var/lib/postgresql
    restart: unless-stopped
